#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 OpenWrt-dist
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=30

CONFIG=mia

uci_get_by_type() {
	local index=0
	if [ -n $4 ]; then
		index=$4
	fi
	local ret=$(uci get $CONFIG.@$1[$index].$2 2>/dev/null)
	echo ${ret:=$3}
}

add_rule(){
for i in $(seq 0 100)
do
	local enable=$(uci_get_by_type macbind enable '' $i)
	local macaddr=$(uci_get_by_type macbind macaddr '' $i)
	local timeon=$(uci_get_by_type macbind timeon '' $i)
	local timeoff=$(uci_get_by_type macbind timeoff '' $i)
	local z1=$(uci_get_by_type macbind z1 '' $i)
	local z2=$(uci_get_by_type macbind z2 '' $i)
	local z3=$(uci_get_by_type macbind z3 '' $i)
	local z4=$(uci_get_by_type macbind z4 '' $i)
	local z5=$(uci_get_by_type macbind z5 '' $i)
	local z6=$(uci_get_by_type macbind z6 '' $i)
	local z7=$(uci_get_by_type macbind z7 '' $i)
	[ "$z1" == "1" ] && Z1="Mon,"
	[ "$z2" == "1" ] && Z2="Tue,"
	[ "$z3" == "1" ] && Z3="Wed,"
	[ "$z4" == "1" ] && Z4="Thu,"
	[ "$z5" == "1" ] && Z5="Fri,"
	[ "$z6" == "1" ] && Z6="Sat,"
	[ "$z7" == "1" ] && Z7="Sun"
	if [ -z $enable ] || [ -z $macaddr ] || [ -z $timeoff ] || [ -z $timeon ]; then
		break
	fi
	if [ "$enable" == "1" ]; then
		nft insert rule inet fw4 MIA meta l4proto tcp ether saddr $macaddr meta hour $timeon-$timeoff meta day { $Z1$Z2$Z3$Z4$Z5$Z6$Z7 } counter jump reject_to_wan
		nft insert rule inet fw4 MIA meta l4proto udp ether saddr $macaddr meta hour $timeon-$timeoff meta day { $Z1$Z2$Z3$Z4$Z5$Z6$Z7 } counter jump reject_to_wan
	fi
	for n in $(seq 1 7)
	do
		unset "Z$n"
	done
done
}

del_rule(){
	local handles=$(nft -a list chain inet fw4 input_wan | grep -E "MIA" | awk -F '# handle ' '{print$2}')
	while [ -n "$handles" ]
	do
		nft delete rule inet fw4 input_wan handle ${handles} 2>/dev/null
	done
}

start(){
	stop
	enable=$(uci get mia.@basic[0].enable)
	[ $enable -eq 0 ] && exit 0
		nft add chain inet fw4 MIA
		nft insert rule inet fw4 input_wan udp dport 53 counter jump MIA comment \"Rule For Control\"
		nft insert rule inet fw4 input_wan tcp dport 53 counter jump MIA comment \"Rule For Control\"
		nft add rule inet fw4 dstnat ip protocol udp ip dport 53 redirect to 53
		nft add rule inet fw4 dstnat ip protocol udp ip dport 53 redirect to 53
		strict=$(uci get mia.@basic[0].strict)
		[ $strict -eq 1 ] && nft insert rule inet fw4 forward_wan counter jump MIA comment \"Rule For Control\"
	add_rule 
}
stop(){
       del_rule
		nft flush chain inet fw4 MIA 2>/dev/null
		nft delete chain inet fw4 MIA 2>/dev/null
}
